default_platform(:ios)

platform :ios do
  desc "Generate screenshots"
  lane :screenshots do
    snapshot(
      scheme: "stepbystep",
      test_without_building: false,
      derived_data_path: "./build",
      devices: [
        "iPhone 15 Pro",
        "iPhone 15 Pro Max"
      ],
      languages: ["ja-JP"],
      clear_previous_screenshots: true,
      override_status_bar: true,
      output_directory: "./screenshots"
    )
  end
  
  desc "Generate and frame screenshots"
  lane :framed_screenshots do
    screenshots
    frame_screenshots(
      path: "./screenshots"
    )
  end
end